[package]
name = "gaul-lang"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
rustyline = "17"
dirs = "6"
strsim = "0.11"
smallvec = { version = "1.15.1", features = ["union"] }

[profile.release]
debug = true